-- Generated by nwg-displays on 2026-05-29 at 17:55:08. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0,
    mirror = "DP-1"
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "2538x1080",
    scale = 1.0
})
