-- Generated by nwg-displays on 2026-09-17 at 13:55:30. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1536x0",
    scale = 1.0,
    mirror = "DP-1",
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "3456x0",
    scale = 1,
    vrr = 0
})
