
# Example windowrule v1
 # windowrule = float, ^(kitty)$
windowrule {
  name = calculator
  float = on
  match:class = ^org.gnome.Calculator$
}

windowrule {
  name = windowrule-2
  float = on
  match:class = ^(blueman-manager)$
}



# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-3
  suppress_event = maximize
  match:class = .*
}



# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-4
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}



#nvim-wl-anywhere
windowrule {
  name = windowrule-5
  float = on
  match:class = ^nvim.wl.anywhere$
}

windowrule {
    name = airctl
    float = on
    match:class = io.github.airctl
}

windowrule {
    name = nmgui
    float = on
    match:class = com.network.manager
}

# windowrule = rounding 0, floating:0, onworkspace:f[1]windowrulev2 = float, class:nvim-wl-anywhere
# windowrulev2 = pin, class:nvim-wl-anywhere
# windowrulev2 = stayfocused, class:nvim-wl-anywhere
# windowrulev2 = size 70% 70%, class:nvim-wl-anywhere

#smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule {
  name = windowrule-6
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = w[tv1]
}

windowrule {
  name = windowrule-7
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = f[1]
}


#from hyde, test for a while
# windowrule = float,initialtitle:^(Open File)$
windowrule {
  name = windowrule-8
  float = on
  match:initial_title = ^(Open File)$
}

windowrule {
  name = windowrule-9
  float = on
  match:title = ^(Choose Files)$
}

windowrule {
  name = windowrule-10
  float = on
  match:title = ^(Save As)$
}

windowrule {
  name = windowrule-11
  float = on
  match:title = ^(Confirm to replace files)$
}

windowrule {
  name = windowrule-12
  float = on
  match:title = ^(File Operation Progress)$
}

windowrule{
    name = suppress_discord
    match:class = ^(discord)*
    no_initial_focus = on
    workspace = 3
}

windowrule{
    name = suppress_zen
    match:class = zen
    focus_on_activate = off
}

windowrule{
    name=albert
    match:class= albert
    border_size=0
    no_blur=on
    no_shadow = on
}

windowrule{
    name=Ulauncher
    match:class= Ulauncher
    match:title = ^(Ulauncher - Application Launcher)*
    border_size=0
    no_blur=on
    no_shadow = on
}

exec-once = sleep 10; hyprctl keyword 'windowrule[suppress_zen]:focus_on_activate on' 
exec-once = sleep 20; hyprctl keyword 'windowrule[suppress_discord]:enable false' 


